# This file contains code automatically generated by a machine.
# It has not been independently verified by any human.
# The generation process is deterministic and tested (not generative AI),
# but not every scenario or risk has been captured in unit tests.
# All code is provided as-is for example purposes only.
# The customer assumes all risks related to the use of this code.


# 
# Silicon Revision: Presumed C0
# 
# Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz
# External LO optimal frequencies: 60 MHz to 12 GHz
# 
# FPGA: v0.0.0
# Device Driver API: v0.0.0
# Device Driver Client: v68.13.7
# Firmware: v0.22.30
# Profile Generator: v0.53.6.0
# Stream Generator Assembly: v0.7.11.0
# Transceiver Evaluation Software: v0.26.0
# ADRV9001 Plugin: v0.26.0

from beginTransmittingiqData2 import *
from beginTransmittingiqData4 import *
import os
import adrv9001_python_wrappers.analog_devices_eval_client_adrv9001_device as adrv9001_types
import adrv9001_python_wrappers.analog_devices_eval_client_fpga9001_device as fpga9001_types
from adrv9001_python_wrappers import flags
flags.DEEP_PRINT = True


def build_str_buff(size, s):
	buff = [0] * size
	ba = bytearray(s, 'utf8')
	for i, v in enumerate(ba):
		buff[i] = v
	return buff



def begin_transmitting(adrv9001_device_0: adrv9001_types.Adrv9001Device, fpga9001_device_0: fpga9001_types.Fpga9001Device):
	global begin_transmitting_iq_data_2
	global begin_transmitting_iq_data_4
	error_code = adrv9001_device_0.radio.ChannelEnableMode_Set(
                                                            adrv9001_types.common_Port_e.TX, 
                                                            adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                            adrv9001_types.adrv9001_ChannelEnableMode_e.ADRV9001_PIN_MODE)

	error_code = adrv9001_device_0.radio.ChannelEnableMode_Set(
                                                            adrv9001_types.common_Port_e.TX, 
                                                            adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                            adrv9001_types.adrv9001_ChannelEnableMode_e.ADRV9001_PIN_MODE)

	error_code, begin_transmitting_iq_data_2 = fpga9001_device_0.dataChain.Data_Set_16IQInterleaved(
                                                                                                 adrv9001_types.common_Port_e.TX, 
                                                                                                 adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                                                                 begin_transmitting_iq_data_2, 
                                                                                                 2048)

	dma_cfg_3 = fpga9001_types.fpga9001_DmaCfg_t(0, True, 0, fpga9001_types.fpga9001_DmaTrigger_e.FPGA9001_DMA_TRIGGER_IMMEDIATE, 
                                 fpga9001_types.fpga9001_CaptureType_e.FPGA9001_CAPTURE_TYPE_DISABLE, 
                                 False)
	error_code = fpga9001_device_0.dataChain.PerformTransfer(
                                                          adrv9001_types.common_Port_e.TX, 
                                                          adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                          dma_cfg_3)

	error_code, begin_transmitting_iq_data_4 = fpga9001_device_0.dataChain.Data_Set_16IQInterleaved(
                                                                                                 adrv9001_types.common_Port_e.TX, 
                                                                                                 adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                                                                 begin_transmitting_iq_data_4, 
                                                                                                 2048)

	error_code = fpga9001_device_0.dataChain.PerformTransfer(
                                                          adrv9001_types.common_Port_e.TX, 
                                                          adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                          dma_cfg_3)

	error_code = adrv9001_device_0.tx.Attenuation_Set(
                                                   adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                   10000)

	error_code = adrv9001_device_0.tx.Attenuation_Set(
                                                   adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                   10000)

	error_code = fpga9001_device_0.tdd.Enable_Set(
                                               fpga9001_types.fpga9001_TddSelect_e.FPGA9001_TDDSELECT_DMA_TX1, 
                                               fpga9001_types.fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_HIGH)

	error_code = fpga9001_device_0.tdd.Enable_Set(
                                               fpga9001_types.fpga9001_TddSelect_e.FPGA9001_TDDSELECT_TX1, 
                                               fpga9001_types.fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_HIGH)

	error_code = fpga9001_device_0.tdd.Enable_Set(
                                               fpga9001_types.fpga9001_TddSelect_e.FPGA9001_TDDSELECT_DMA_TX2, 
                                               fpga9001_types.fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_HIGH)

	error_code = fpga9001_device_0.tdd.Enable_Set(
                                               fpga9001_types.fpga9001_TddSelect_e.FPGA9001_TDDSELECT_TX2, 
                                               fpga9001_types.fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_HIGH)

	print("Now transmitting.")

