# This file contains code automatically generated by a machine.
# It has not been independently verified by any human.
# The generation process is deterministic and tested (not generative AI),
# but not every scenario or risk has been captured in unit tests.
# All code is provided as-is for example purposes only.
# The customer assumes all risks related to the use of this code.


# 
# Silicon Revision: Presumed C0
# 
# Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz
# External LO optimal frequencies: 60 MHz to 12 GHz
# 
# FPGA: v0.0.0
# Device Driver API: v0.0.0
# Device Driver Client: v68.13.7
# Firmware: v0.22.30
# Profile Generator: v0.53.6.0
# Stream Generator Assembly: v0.7.11.0
# Transceiver Evaluation Software: v0.26.0
# ADRV9001 Plugin: v0.26.0

import os
import adrv9001_python_wrappers.analog_devices_eval_client_adrv9001_device as adrv9001_types
import adrv9001_python_wrappers.analog_devices_adrv9001_profile_types as adrv9001_profile_types
from adrv9001_python_wrappers import flags
flags.DEEP_PRINT = True


def build_str_buff(size, s):
	buff = [0] * size
	ba = bytearray(s, 'utf8')
	for i, v in enumerate(ba):
		buff[i] = v
	return buff



def configure(adrv9001_device_0: adrv9001_types.Adrv9001Device):
	print("Configuring features.")

	gp_int_mask_1 = 0
	error_code, gp_int_mask_1 = adrv9001_device_0.gpio.GpIntMask_Get(gp_int_mask_1)

	print("GpIntMask_Get parameter 'gpIntMask' read back as '" + str(gp_int_mask_1) + "'\n")

	error_code = adrv9001_device_0.gpio.GpIntMask_Set(16)

	error_code = adrv9001_device_0.tx.AttenuationMode_Set(
                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                       adrv9001_types.adrv9001_TxAttenuationControlMode_e.ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI)

	error_code = adrv9001_device_0.tx.Attenuation_Set(
                                                   adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                   10000)

	error_code = adrv9001_device_0.tx.AttenuationMode_Set(
                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                       adrv9001_types.adrv9001_TxAttenuationControlMode_e.ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI)

	error_code = adrv9001_device_0.tx.Attenuation_Set(
                                                   adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                   10000)

	power_saving_cfg_7 = adrv9001_types.adrv9001_PowerSavingAndMonitorMode_ChannelPowerSavingCfg_t(
                                                                          adrv9001_types.adrv9001_PowerSavingAndMonitorMode_ChannelPowerDownMode_e.ADRV9001_POWERSAVINGANDMONITORMODE_CHANNEL_MODE_DISABLED, 
                                                                          adrv9001_types.adrv9001_PowerSavingAndMonitorMode_ChannelPowerDownMode_e.ADRV9001_POWERSAVINGANDMONITORMODE_CHANNEL_MODE_DISABLED)
	error_code = adrv9001_device_0.powerSavingAndMonitorMode.ChannelPowerSaving_Configure(
                                                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                                                       power_saving_cfg_7)

	error_code = adrv9001_device_0.powerSavingAndMonitorMode.ChannelPowerSaving_Configure(
                                                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                                                       power_saving_cfg_7)

	delays_9 = adrv9001_types.adrv9001_ChannelEnablementDelays_t(170680, 169206, 170680, 0, 0)
	error_code = adrv9001_device_0.radio.ChannelEnablementDelays_Configure(
                                                                        adrv9001_types.common_Port_e.TX, 
                                                                        adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                                        delays_9)

	error_code = adrv9001_device_0.radio.ChannelEnablementDelays_Configure(
                                                                        adrv9001_types.common_Port_e.TX, 
                                                                        adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                                        delays_9)

	error_code = adrv9001_device_0.bbdc.adi_adrv9010_bbdc_LoopGain_Set(
                                                                    adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                                    65536)

	error_code = adrv9001_device_0.bbdc.adi_adrv9010_bbdc_LoopGain_Set(
                                                                    adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                                    65536)

	tracking_cals_chan_tracking_cal_mask_13 = [adrv9001_profile_types.adrv9001_TrackingCalibrations_e.ADRV9001_TRACKING_CAL_RX_BBDC | adrv9001_profile_types.adrv9001_TrackingCalibrations_e.ADRV9001_TRACKING_CAL_RX_RFDC | adrv9001_profile_types.adrv9001_TrackingCalibrations_e.ADRV9001_TRACKING_CAL_RX_QEC_FIC] * 2
	tracking_cals_13 = adrv9001_profile_types.adrv9001_TrackingCals_t(
                                               tracking_cals_chan_tracking_cal_mask_13)
	error_code = adrv9001_device_0.cals.Tracking_Set(tracking_cals_13)

