# This file contains code automatically generated by a machine.
# It has not been independently verified by any human.
# The generation process is deterministic and tested (not generative AI),
# but not every scenario or risk has been captured in unit tests.
# All code is provided as-is for example purposes only.
# The customer assumes all risks related to the use of this code.


# 
# Silicon Revision: Presumed C0
# 
# Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz
# External LO optimal frequencies: 60 MHz to 12 GHz
# 
# FPGA: v0.0.0
# Device Driver API: v0.0.0
# Device Driver Client: v68.13.7
# Firmware: v0.22.30
# Profile Generator: v0.53.6.0
# Stream Generator Assembly: v0.7.11.0
# Transceiver Evaluation Software: v0.26.0
# ADRV9001 Plugin: v0.26.0

import os
import adrv9001_python_wrappers.analog_devices_eval_client_adrv9001_device as adrv9001_types
from adrv9001_python_wrappers import flags
flags.DEEP_PRINT = True


def build_str_buff(size, s):
	buff = [0] * size
	ba = bytearray(s, 'utf8')
	for i, v in enumerate(ba):
		buff[i] = v
	return buff



def prime(adrv9001_device_0: adrv9001_types.Adrv9001Device):
	print("Priming channels.")

	error_code = adrv9001_device_0.tx.AttenuationMode_Set(
                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_1, 
                                                       adrv9001_types.adrv9001_TxAttenuationControlMode_e.ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI)

	error_code = adrv9001_device_0.tx.AttenuationMode_Set(
                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_2, 
                                                       adrv9001_types.adrv9001_TxAttenuationControlMode_e.ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI)

	error_code = adrv9001_device_0.radio.Channel_ToPrimed(
                                                       adrv9001_types.common_Port_e.TX, 
                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_1)

	error_code = adrv9001_device_0.radio.Channel_ToPrimed(
                                                       adrv9001_types.common_Port_e.TX, 
                                                       adrv9001_types.common_ChannelNumber_e.CHANNEL_2)

